name: EAS

on:
    push:
        branches:
            - main
jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: 🏗 Setup repo
              uses: actions/checkout@v4

            - name: 🏗 Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc

            - name: 🏗 Setup EAS
              uses: expo/expo-github-action@v8
              with:
                  eas-version: latest
                  token: ${{ secrets.EXPO_TOKEN }}

            - name: 📦 Install dependencies
              run: npm i

            - name: 🚀 Create update
              run: eas update --auto --non-interactive
